version: '3.8'
services:
  db:
    image: mysql-projeto-ecommerce
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: ecommerce
    ports:
      - "3306:3306"
    networks:
      - devs2blu-network
  backend-projeto-ecommerce:
    image: backend-projeto-ecommerce
    restart: always
    build: ./projeto-ecommerce
    working_dir: /projeto-ecommerce
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./projeto-ecommerce:/projeto-ecommerce
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - devs2blu-network

  frontend-projeto-ecommerce:
    image: atbatw146/frontend-projeto-ecommerce
    expose:
      - 4200
    ports:
      - 4200:4200
    restart: on-failure
    volumes:
      - ./projeto-ecommerce:/projeto-front-ecommerce
    build: ./projeto-front-ecommerce
    working_dir: /projeto-front-ecommerce
    command: "npm install && npm install -g @angular/cli@13.2.5 && ng serve --open --host 0.0.0.0 --port 4200 --disable-host-check"
    links:
      - backend-projeto-ecommerce
    depends_on:
      - backend-projeto-ecommerce
    networks:
      - devs2blu-network
networks:
    devs2blu-network:
        driver: bridge